=== krsdntr/krisdigitalstudio/.astro/collections/blocks.schema.json
{
  "$ref": "#/definitions/blocks",
  "definitions": {
    "blocks": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "componentName": {
          "type": "string"
        },
        "orderId": {
          "type": "number"
        },
        "title": {
          "type": "string"
        },
        "subtitle": {
          "type": "string"
        },
        "media": {
          "type": "string"
        },
        "ctaText": {
          "type": "string"
        },
        "ctaLink": {
          "type": "string"
        },
        "secondaryCtaText": {
          "type": "string"
        },
        "secondaryCtaLink": {
          "type": "string"
        },
        "checklists": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== krsdntr/krisdigitalstudio/src/content/blocks/profil.json
{
  "name": "profil",
  "componentName": "Profile",
  "orderId": 2,
  "title": "About me",
  "subtitle": "Currently diving into how biochemistry and technology can work together to simplify research, learning, and everyday problem-solving. I share what I learn from scientific insights to AI tools and experiments. Open to collaborations and conversations around research, education, and creative tech applications. Let’s connect, grow, and build something valuable",
  "media": "https://prod-files-secure.s3.us-west-2.amazonaws.com/575abe12-833e-4e76-9279-9ed1afab19f7/2aab5c6f-8cbb-4102-b3c2-11dd9ac995fa/Generated_Image_September_20_2025_-_12_13AM.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466UW7RCP2M%2F20260302%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260302T075610Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjELf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLXdlc3QtMiJHMEUCIHzce%2B8CM5MyspsxLziMzsjM4ZjmHKxsNChXNJJoUaZ7AiEA4pTCquuDyhJATKsEBpCwhszKeo9WR26xwSW%2BwxFaFDcqiAQIgP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw2Mzc0MjMxODM4MDUiDJh0SVQ72CEKEAiIxSrcA00qHdSap%2Fg5fb7IBnDJ0Oe6ZeiLMmUK9m37EYfaMWdZ6eXydX4Zna8wVSeRMtD2l9dGSDH42GtvfVzxDQf9Ot%2BD8PpLi%2FsFsAtr%2FBtoP1XD25wIBC3bgBJ4S2lS0W8sCrjmPbk5DEMN4tIoWiGjmMG4twFSLgnFzdEIr9h7NzWmUYV0MKWcqSyDH7ONNkEXLZMprwfJ4HfBiPyfDu3%2FG%2BWKOKVLqT2mFKpHtVMmxDBigBtGbXoWpSbMK90V3JZAZJXzVNoao08pmnMDqLxHxk9iVx7moL5JuDcI%2FtFCpDc%2BiofNj1iPRLDgnne%2B%2FtCWoWxHqrARpEr1p2XbcQg34seECX%2BxIAnvgQ2FszcCreBHr3adTNOy1bodf6O9OpoN2FoF7%2BQU4UE763dyprCJ6%2FlEI1NsaBPd7dj054Tl4F9yZrOF4kNKqQTXOuNHlw%2Fpdo63NhHHTpjYG1zQkp2HnaVRdeCjpUrmtG9uSyJ%2BIRbTb3nDkw3hV2u8hM8A3OuU8%2BW8YHXr6%2Fe2F%2FrDwgHoduUmCgIYybBY5PX0NomoMF2G6FyRw0VqCXbLmo39uD8ESL4h7yZV9bd9qBopOL9zCtfyyHHi6zjTfIGX1RpnrtAS3qwjdgdH1criMHK1MKjtlM0GOqUBhY7LLob2q8evS4%2B5LBpdeqa0Qq%2FtY4qbX%2BInYcgyRtL4OJKujtjlCPVPsoyBpUn3o9gODMwlZmAro%2FJtYYXbH1SmICCaamLx9yJJyGZjnhROeQ4pnfXFCfwzn6fC0cl539iDlgayOZTGBS6C4e%2BPg%2BPvFXmvip1%2FaBDOMUP4LmzxZUrKSSIGM5IHGO%2BTgK8ePEX8UNgH2aMxXsBx4BUYM5U48SNT&X-Amz-Signature=dde07419c784a4531e50eadc0e8e057cb81ac9635d0cbf954881304060bc58e8&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
  "ctaText": "",
  "ctaLink": "",
  "secondaryCtaText": "",
  "secondaryCtaLink": "",
  "checklists": "Biochemistry, IPB University, Web Development, Digital Enthusiast"
}

=== krsdntr/krisdigitalstudio/src/content/blocks/hello-.json
{
  "name": "hello-",
  "componentName": "Hero",
  "orderId": 1,
  "title": "I’m Kris",
  "subtitle": "Building intelligent web applications and digital workspaces to accelerate academic research and data management.",
  "media": "",
  "ctaText": "",
  "ctaLink": "",
  "secondaryCtaText": "",
  "secondaryCtaLink": "",
  "checklists": "Full-Stack Development, AI Integration, Biochemistry"
}
